project_name: gobuild

release:
  github:
    owner: caixw
    name: gobuild
  name_template: '{{.Tag}}'

builds:
- id: gobuild

  goos:
  - darwin
  - linux
  - windows

  goarch:
  - amd64
  - arm64

  ignore:
  - goos: windows
    goarch: arm64

  main: ./cmd/gobuild

  binary: gobuild

  flags:
  - -trimpath

  ldflags:
  - -s -w -X github.com/caixw/gobuild/internal/cmd.meta={{time "20060102"}}.{{.FullCommit}} -X main.version={{.Tag}}

brews:
- tap:
    owner: caixw
    name: homebrew-brew
  url_template: "https://github.com/caixw/gobuild/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  folder: Formula
  homepage: "https://github.com/caixw/gobuild"
  description: Go 热编译工具
  license: MIT

archives:
- builds:
  - gobuild
  replacements:
    darwin: macOS
  format_overrides:
  - goos: windows
    format: zip
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  skip: true
