name: Release
on:
  create:
    tags:
      - 'v*'
      - '!v*-alpha'
      - '!v*-beta'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest

    steps:

      - name: setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: release
        uses: goreleaser/goreleaser-action@v4
        with:
          workdir: ./cmd/gobuild
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW }}

